### ISSUE TITLE
Make item kind checking public

### ISSUE THREAD

**Issue by cojoj** [JohnSundell/Files#12] opened 2017-05-29 08:36 UTC
In the current implementation there's a privet extension on `FileManager` with this cool method: `itemKind(atPath path: String) -> FileSystem.Item.Kind?`.
I'd love to see something like this being public, so it's easier to decide what we _can_ do with this item.

We can make current implementation `public` by simply creating wrapper in `FileSystem`, but the problem is that this method _relies_ of existence of this `Item`, so we can't simply say: `itemKind(atPath: "fake/path/to/something.txt")`, cause we'll get `nil`. We can use `URL`'s method called `hasDirectoryPath()`, but strangely, Xcode shows warning, so I had to put `#available` check (which is kinda limiting...) as this API is available since iOS 9.

This kind of functionality can bring a nice and unified way of creating new `Items` at specific path, like: `createItem(atPath: String) -> Item` and `createItemIfNeeded(atPath: String) -> Item`.

What do you guys think about having a method just for checking the type of `Item` at specified path without requiring existence? I'm still not sure whether this isn't something beyond the scope of Files?

**Comment by JohnSundell** [comment] 2017-05-29 18:50
It's very much by design (so far) that Files doesn't have any public API that returns `Item`, because ideally you'd want to know whether your dealing with a file or a folder. Do you have a concrete usecase in mind @cojoj that requires you to deal with an `Item` without knowing its type?

**Comment by cojoj** [comment] 2017-05-29 19:09
Not with `Item` directly (that just popped up in my head), but... Here's what I'm working on currently:
User provides as a command line parameter a path (could be a folder or a file) and I want to know what is it before I call a specific method from `FileSystem`. With the current implementation I have to determine up-front which method I'll invoke - file or folder creation, but with proper abstraction it wouldn't matter, right?

**Comment by JohnSundell** [comment] 2017-05-29 19:13
Here's one way to do it:

```swift
let path = CommandLine.arguments[1]

let folder = try? Folder(path: path) {
    // It's a folder!
} else if let file = try? File(path: path) {
    // It's a file!
} else {
    // Create something new
}
```

Would the above work? 🙂

**Comment by cojoj** [comment] 2017-05-29 19:19
Well, looks like my brain isn't working properly in that case 😂 I'll check it later (or tomorrow) and eventually close this issue... But you've achieved it too easily, I don't believe you 😜

**Comment by JohnSundell** [comment] 2017-05-29 19:34
Haha 🤣 Sure, let me know how it goes 👍

**Comment by cojoj** [comment] 2017-05-30 15:25
@JohnSundell I don't know yet what's wrong, but:

```swift
let path: String = "/boot/grub/grub.conf"

do {
    let test = try File(path: path)
} catch {
    print(error)
}
```

Gives me `Invalid path given: /boot/grub/grub.conf`, but clearly should work, right?

**Comment by JohnSundell** [comment] 2017-05-30 16:21
Yeah `File(path:)` can only be used on files that already exist. Otherwise you'll have to use the `FileSystem` APIs or use the parent `Folder` to create a new file. That's why I used `try?` in my example code above, since it returns `nil` in case the file is missing 🙂

**Comment by JohnSundell** [comment] 2017-06-03 18:27
@cojoj Anything else I can help with here, or can we close this one? 😄

**Comment by cojoj** [comment] 2017-06-04 19:46
![](https://goo.gl/images/SQUJbl)

**Closed** 2017-06-04 19:47 UTC
Labels: question
